@Bl.Webhook.Sample_HostAddress = http://localhost:5158

POST {{Bl.Webhook.Sample_HostAddress}}/product/radom
Content-Type: application/json
{

}


POST {{Bl.Webhook.Sample_HostAddress}}/webhook/in-memory
Content-Type: application/json
{
  "eventType": "product.create",
  "webhookUrl": "https://webhook.site/9e550196-b177-4d1f-afba-aee84594a059"
}
